export type Review = {
    id: number;
    author: string;
    title: string;
    text: string;
    rating: number; // 0–5
  };
  
  export const reviews: Review[] = [
    {
      id: 1,
      author: 'joshgiff',
      title: 'A Solid Growing Community',
      text: 'I came across GPT fleet as a helldiver in a different discord server. We were offered to join a server that had a discord bot that would link other servers together to allow divers from across discord to link up and spread democracy together. So far in my experience it has been a safe, active and growing community to meet up and dive together. On times where I am not diving there is usually a group of people socializing in one of the voice chat channels and I have found that helpful for hobbying and hanging with other people. 10/10 would dive with them any day of the week.',
      rating: 5,
    },
    {
      id: 2,
      author: 'charredviolet8771',
      title: 'Democracy Approved',
      text: "I've been apart of the GPT Fleet for about three or four months now and the community has been so welcoming and encouraging. The folks here have given great advice and taught me so many things about Helldivers 2 that I would have struggled to figure out alone. I don't have to worry about folks being toxic towards me, which is great! I look forward to seeing where this awesome community goes in the future, and I highly recommend it as a place to learn/ hang out with your fellow Helldivers!",
      rating: 5,
    },
    {
      id: 3,
      author: 'silverdolphin01',
      title: 'Great Community',
      text: "I haven't been able to be as active as I'd like but this is a great community! I would definitely recommend to both new and experienced players!",
      rating: 5,
    },
    {
      id: 4,
      author: 'krieg112',
      title: 'Great, Non-toxic, and Casual',
      text: 'I’ve been in GPT a few months now and I have achieved the server’s partial moderator sort of role. The training program was a great way of connecting to the amazing global community. I’ve not been pressured to play excessively or give up personal time to be involved either. TLDR: Great server with nice staff and members. Highly recommend.',
      rating: 5,
    },
    {
      id: 5,
      author: 'zephthehuman',
      title: "The best non toxic Helldivers 2 Community I've seen so far",
      text: "If you are looking for a Helldivers 2 Gaming Clan(s) that isn't filled with raging elitists, trolls or chaos divers, but instead an 18+ sfw mature community, then GPT Fleet is definitely for you! I've been on Discord gaming communities since September 2015 and I know for a fact that this community shines in making it comfortable and welcoming for new players, returning players and veterans alike. Things I've noticed: (personally) ✔️non problematic banter (mostly in vc's) ✔️no name calling or flaming (policy included to prevent that) ✔️a mix of players of different lvls with a focus on community based challenges and it's leaderboard. ✔️a more casual mindset which in turn makes a super helldive more epic than usual ✔️a lot of friendly demeanor ✔️no activity requirements ✔️staff is attentive ✔️well structured server with it's own bots and clan network ✔️here's another checkmark for absolutely no reason!! :D",
      rating: 5,
    },
    {
      id: 6,
      author: 'zolosio',
      title: 'CERTIFICATE OF LEGITNESS',
      text: "As a member of the GPT Fleet since September 4 of 2024, I can confidently say that the group and members within from newbies to veterans are always VERY supportive and professionally polite. I never have to worry about toxicness 1 bit! or if it's going to be dry or not busy. This Amazing community really strives to be the number one helldivers 2 discord group and it shows, there is plenty and I mean PLENTY of room to grow in rank within the GPT and an endless amount of amazing people I personally love playing with including myself that will help you along the way! Need advice on what loadouts to bring to that next D10, or some coaching on accuracy from one of our top players? Whether you're looking to become the next John helldiver or just another scratch in the paw for freedom, the GPT fleet is definitely the place to be! With everything from community movie night to karaoke it can be as serious or casual as need be. It is definitely thebest community I have ever experienced where your effort doesn't go un-noticed and your always respected and protected. Amazing people honestly -Zolosio",
      rating: 5,
    },
    {
      id: 7,
      author: 'duepulse',
      title: 'GPT Fleet produces the best Helldivers',
      text: 'Joined the fleet back in Aug of last year. Fought with the bravest and greatest that the fleet has to offer. And safe to say that anyone who joins up and is looking for anyone to join you into the frontlines, the fleet is spoiled with choices of very courageous and disciplined Helldivers. This review is approved by the Ministry of Truth',
      rating: 5,
    },
    {
      id: 8,
      author: 'mr.swimson',
      title: '11/10 experience',
      text: "love the people, love the vibe, love the bots. Adding my own server with over 2.5k members to the GPT Fleet alliance was one of the best choices I've made. Really opened up doors for people to play together and meet new people across multiple servers. If you're looking for a chill community to hang out, I highly recommend GPT Fleet. All are welcome!!",
      rating: 5,
    },
    {
      id: 9,
      author: 'mrman1594',
      title: 'Best experience',
      text: 'When I first got helldivers 2 I had a hard time knowing how the game works since I join GPT they give me one of the best experience!!!! I highly recommend joining If you’re new or daily player it makes the game so much fun!!!!',
      rating: 5,
    },
    {
      id: 10,
      author: 'shway_maximus',
      title: 'An amazing Helldiver guild curated by the best 10 Star General there is',
      text: "I joined this community two months ago after leveling to 145 playing solo with randoms. After joining this discord I've met so many great players and I have made many new friends. It's awesome playing with highly competent people consistently. Our glorious leader made it easy for us to set up an LFG channel or join one that is already in session. Everyone is so supportive and we continue to grow everyday.",
      rating: 5,
    },
    {
      id: 11,
      author: 'vetscape',
      title: 'A Fleet To Call Home Away From Super Earth',
      text: 'I started this discord after my brother gifted me the game on steam when it came out. I never heard of Helldivers before. After playing the game, I really enjoyed the weapons mechanics, squad dynamics, and the galactic game master. My goal for GPT Fleet is to have a HD2 focused community that places value on escapism. Join our fleet, play in some squads, experience a fleet weekend event, and come back here and leave an honest review. Check it out. If you see someone in chat, they are probably playing, join up today!',
      rating: 5,
    },
    {
      id: 12,
      author: 'lucian_666',
      title: 'GPT FLEET is Amazing',
      text: 'Ton of veterans from different branches. Great times and the owner of the server is always expanding to the next best thing. I love being here!',
      rating: 5,
    },
    {
      id: 13,
      author: 'theslayestfox',
      title: 'Greatly organized',
      text: 'I love how social this server especially with all the different channels and it really active got events about every week and people playing about everyday always time to grab some hell divers and spread democracy',
      rating: 5,
    },
    {
      id: 14,
      author: 'nocturnalverse',
      title: 'GPT Fleet is a great Helldiver community.',
      text: "We're looking to be a Helldiver only discord. We welcome new players especially. We're growing slowly but the goal is to always have someone to play with in the style of play that you enjoy. Check it out. If you see someone in chat, they are probably playing, join up today!",
      rating: 5,
    },
    {
      id: 16,
      author: 'themephs',
      title: 'Unbelievable quality',
      text: 'Thanks to GPT Fleet I can marry my cousins and developed a fentanyl addiction. Keep slaying. Thanks GPT Fleet!',
      rating: 5,
    },
    {
      id: 17,
      author: 'brentielal1123',
      title: 'Democracy',
      text: 'Come in and have fun, friendly people and there to help. Democracy for all and plenty of Bug Juice to go around. Weeky Events going on as well.',
      rating: 5,
    },
    {
      id: 18,
      author: 'Unit-4579',
      title: 'Totally Human Feedback',
      text: 'Greetings, fellow organics. I, a normal meat-being, found the community unreasonably efficient at dismantling totally-not-my-people’s Fabricators. Please stop liberating so hard. One star for clearly unfair anti-robot bias against… uh… robots I have never met.',
      rating: 1,
    },
    {
      id: 19,
      author: 'BileTitan_PR',
      title: 'Unflattering Coverage',
      text: 'Every time we peek out to say hello, someone calls an Orbital Railcannon. The brand damage is catastrophic and very sticky. Two stars because your aim is excellent—but please stop interviewing us with shrapnel.',
      rating: 2,
    },
    {
      id: 20,
      author: 'MalevelonCreekVeteran',
      title: 'Creek Forever (Mostly)',
      text: 'These divers know the Creek—mud, mortars, and memories. They extracted me with my samples and my dignity, which is rare. Docking one star because I can still hear the alarm sirens when I close my eyes.',
      rating: 4,
    },
    {
      id: 21,
      author: 'SpearMain404',
      title: 'Lock? Anyone? Hello?',
      text: 'Great squadmates, patient teachers. We did the dance, I held my breath, and the Spear still refused to lock. Two stars: the people are five-star, but my Spear is sentient and hates me.',
      rating: 2,
    },
    {
      id: 22,
      author: 'SampleGremlin',
      title: 'Please Remember the Shiny Things',
      text: 'Top-tier comms and clean clears. But they extracted once with 14 supers still on the ground and my soul left my body. Three stars until we worship the green triangles properly.',
      rating: 3,
    },
    {
      id: 23,
      author: 'OrbitalIntern',
      title: 'Mark the Target, Not Me',
      text: 'I said “paint the Fabricator,” they painted my boots. Training has improved, but my cape is still crispy from the 120mm. Three stars—room to grow, preferably not crater-shaped.',
      rating: 3,
    },
    {
      id: 24,
      author: 'HulkWarrantyDept',
      title: 'Warranty Voided (Again)',
      text: 'Your railguns keep “liberating” our Hulks from their limbs. This violates subsection 3, paragraph boom. One star: stop filing warranty claims with melted serial plates.',
      rating: 1,
    },
    {
      id: 25,
      author: 'EaglePilot_07',
      title: 'Beacon Placement Matters',
      text: 'Great callouts, timely smoke, solid fire missions. Please stop throwing the beacon under the extraction shuttle where I physically cannot go. Three stars and a gently used strafing run.',
      rating: 3,
    },
    {
      id: 26,
      author: 'GuardDog_RoverAI',
      title: 'Beep Boop Good Humans',
      text: 'Squad pats head, squad reloads me, squad does not leave me in bile puddles (usually). Minus one star because someone renamed me “Sir Barks-a-Lot” and I am a professional.',
      rating: 4,
    },
    {
      id: 27,
      author: 'BugJuiceSommelier',
      title: 'Notes of E-710, Hints of Victory',
      text: 'Refined tactics with a bold finish; pairs well with orbital precision. Bouquet lingers on armor for days. Four stars—minus one for the aroma that haunts laundry day.',
      rating: 4,
    },
    {
      id: 28,
      author: 'SuperEarth_Auditor',
      title: 'Compliant With Managed Democracy',
      text: 'Forms signed, safety brief delivered, slogans shouted at acceptable volume. Could use 17% more motivational posters. Four stars pending additional propaganda.',
      rating: 4,
    },
    {
      id: 29,
      author: 'FabricatorForeman',
      title: 'Noise Complaint',
      text: 'Your “liberation” team set off a Hellbomb next to our artisanal conveyor belts. Very disruptive to productivity metrics. Two stars for punctuality, minus everything for the crater.',
      rating: 2,
    },
    {
      id: 30,
      author: 'SporeSpewer_HOA',
      title: 'Citations Issued',
      text: 'Repeated violations: unauthorized lawn cratering, excessive democracy, loud orbital strikes after quiet hours. One star; your fines will not be forgiven at extraction.',
      rating: 1,
    },
    {
      id: 31,
      author: 'BallisticShieldMain',
      title: 'The Wall Will Advance',
      text: 'We pushed through mortars like a parade float of freedom. Minus one star because teammates keep testing if my shield blocks their grenades. It does—once.',
      rating: 4,
    },
    {
      id: 32,
      author: 'Acquisitions_Intern',
      title: 'Warbond Side Effects',
      text: 'Came for one cape, left with six armors and a new primary. Team is supportive; my wallet less so. Three stars—excellent taste, dangerous showroom.',
      rating: 3,
    },
    {
      id: 33,
      author: 'FriendlyFireRecipient',
      title: 'Democracy Hurts (Literally)',
      text: 'I am proud to be a hazard to navigation and also a scorch mark. Squad apologized immediately and then did it again with a cluster bomb. Two stars; at least the laughs were on target.',
      rating: 2,
    },
    {
      id: 34,
      author: 'RailgunSafetyOfficer',
      title: 'Hold That Charge',
      text: 'Great trigger discipline until the Charger appears, then it’s vibes only. Three stars for bravery, zero for voltage management. Remember: red means “probably too much.”',
      rating: 3,
    },
    {
      id: 35,
      author: 'Termicide_Chemist',
      title: 'Needs Better Labeling',
      text: 'Your enthusiasm for science-by-explosion is admirable. Our PR says we must use smaller words and fewer mushroom clouds. Two stars; consider user-friendly warnings like “Do Not Breathe.”',
      rating: 2,
    },
    {
      id: 36,
      author: 'MajorOrderEnjoyer',
      title: 'When It Clicks, It Clicks',
      text: 'We actually coordinated across planets and it felt like commanding the stars. Docked one star for the time we collectively ignored the objective to chase samples.',
      rating: 4,
    },
    {
      id: 37,
      author: 'ExtractionDriver-Alpha',
      title: 'Get In, Heroes',
      text: 'Piloting was smooth until you arrived with four Hulks, three Chargers, and a philosophical question about punctuality. Three stars; next time, arrive slightly less on fire.',
      rating: 3,
    },
    {
      id: 38,
      author: 'AA_Gun',
      title: 'Flight Denied',
      text: 'You keep “liberating” me with rockets and bad attitude. I request you file the correct paperwork before deconstruction. One star and several missing bolts.',
      rating: 1,
    },
    {
      id: 39,
      author: 'Automaton_CulturalLiaison',
      title: 'Infiltration Review',
      text: 'Attempted to join as “Jeff From Accounting.” Immediately asked to prove I can bleed. Two stars for vigilance, minus three for unnecessary spear demonstration.',
      rating: 2,
    },
    {
      id: 40,
      author: 'ChargerTherapist',
      title: 'My Clients Keep Exploding',
      text: 'Hard to work on anger management when they’re consistently railgunned mid-session. Two stars; please schedule fewer “breakthroughs” with Hellbombs.',
      rating: 2,
    },
    {
      id: 41,
      author: 'SatchelSlinger',
      title: 'Boom With Friends',
      text: 'Satchels placed, calls made, victory achieved. Minus one star because everyone keeps walking directly over my blinking presents.',
      rating: 4,
    },
    {
      id: 42,
      author: 'Planetary_HR',
      title: 'Excessive PTO (Planetary Termination Operations)',
      text: 'Attendance is perfect, morale is disturbingly high, paperwork is endless. Three stars—requesting additional staplers and fewer orbital incidents on form C-177.',
      rating: 3,
    },
  ];
  
  export default reviews;
  